# Generated by Django 3.2.5 on 2021-07-21 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Required. 128 characters or fewer.', max_length=128, verbose_name='product brand title')),
                ('product', models.CharField(help_text='Required. 128 characters or fewer.', max_length=128, verbose_name='product title')),
                ('slug', models.SlugField(help_text='Required. 128 characters or fewer. Letters, numbers, hyphens and underscores.', max_length=128, verbose_name='product slug')),
                ('image', models.ImageField(default='default/product.png', upload_to='product')),
                ('description', models.TextField(help_text='Required', verbose_name='product description and/or specifications')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='A positive decimal number. Defaults to numeric zero.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price for a single item')),
                ('quantity', models.IntegerField(default=0, help_text='A positive integer number. Defaults to integer zero.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of available items')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
